### ISSUE TITLE
Notes from Lab 1 Meeting

### ISSUE THREAD

**Issue by alistair-clark** [UBC-MDS/DSCI_522_Group_412#1]
Hi team. Here's the tasks we discussed during our January 2017 meeting:

**0. Project Setup**
- **Alex** to complete initial Github is setup - DONE!
- **Alistair** setup folders: src, data, fig (or img), repo (look at one of Tiffany's repo)

**1. Team Contract**
- **Alistair** and **Aakanksha** to send **Alex** github link to team contracts
- **Alex** to complete first draft and send to team on slack
- **Alistair** and **Aakanksha** to review and provide comments

**2. Code of Conduct**
- **Alistair** and **Aakanksha** to send **Alex** github link to team contracts
- **Alex** to complete first draft and send to team on slack
- **Alistair** and **Aakanksha** to review and provide comments

**3. CONTRIBUTING**
- **Alex** to upload contributing

**4. LICENSE** - DONE
**5. Proposal**
- **Aakanksha** push first draft of proposal on Saturday
- **Alistair** and **Alex** to review and provide comments on Sunday morning

**6. Script to download & save data**

- **Alistair** create first draft and upload to repo on Friday
- **Alex** to review and improve
- **Aakanksha** to review and improve

**7. EDA file**
- **Alistair** create first draft and upload to repo on Friday
- **Alex** to review and improve
- **Aakanksha** to review and improve

**8. Final submission:** 
- **Aakanksha** to create a release on your project repo named v0.1 and send on slack

**Comment by aakanksha023** [comment]
@YueJiangMDSV 
* In the **Code of Conduct** file following markdown formatting changes could be incorporated:

This Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html), version 1.4, and the [UBC Data Science 100 CoC](https://github.com/UBC-DSCI/dsci-100/blob/master/CODE_OF_CONDUCT.md)

* Team Contract: No further input
* Minor typo correction in 'Contributing.md' - Thank you for taking the time to contribute!
          - Gentle reminder to update the code of conduct link in contributing.md

**Comment by YueJiangMDSV** [comment]
Thanks @aakanksha023 !
I updated the Code of Conduct and the Contributing.md as you suggested.

**Comment by YueJiangMDSV** [comment]
I haven't looked at the proposal yet, but there is one thing about the proposal please keep in mind:
From milestone1 file:
**the proposal should be written in the README.md file in the root of your public GitHub.com repo.**

**Comment by aakanksha023** [comment]
Resolved.

**Comment by aakanksha023** [comment]
### Reviewed and edited eda file
- [link_to_commit](4c6f0c468575248d4cb6a8013e3e08eedbc7f6d5)

@YueJiangMDSV : I had the following thoughts about the chunk of code you added:

- We are transforming the `+` and `-` labels to 1/0 in y_train. But ,then we'll have to do the same transformation on y_test. I think, to strictly abide by the golden rule of not touching test data. we can remove this transformation. (Even though it doesn't change anything in the data)
- I'm unable to format the 0/1 at the top of the plots indicating approved/not approved
     - Can't increase the size or bold them
     - Can't figure out how to replace 0/1 with text "Not approved"/"Approved"

Rest were minor grammatical fixes and deletion of repeated conclusions. Also did small modifications in the code to remove repetitions and improve aesthetics.

**Comment by YueJiangMDSV** [comment]
@aakanksha023 Thanks for the edit. About the EDA, I think there are three plots that need improvement: 
1. The Bank Customer plot: why it says undefined? In my original plot, altair can discover the categories in the data
2. EducationLevel: the plot is definitely overplotting. The bars are top of each other. I think there should be a better way to show it.
3. Ethnicity: the same as above. There are some overplotting in it. 

As for the proposal, I think:
1. In the Analysis Plan part, Logistic regression is not an ensemble method. Random Forest is the ensemble method. Maybe you can switch Logistic regression and Random Forrest. 
2. Overall it is well-written. I saw Tiffany shared her example of the proposal. Did you look at that? It may be helpful if you want to update the proposal.

**Comment by alistair-clark** [comment]
Hi team! A few comments on this thread:

**EDA:**

- I think it's fine to do the `+` and `-` labels to 1/0 in y_train. Next week we'll have to put all of these wrangling steps into a pipeline (including others like OHE and scaling). It doesn't break the golden rule because we'll apply the same pipeline to our test set when we check our final model.
- To fix the overplotting we could try either (1) removing the argument `size = 40` in the `make_plot` function or (2) increasing the plot width argument to 400 or 600.

**Proposal:**
- based on Tiffany's example, I suggest updating our research question to: "Given information on individual's credit application, will the application be approved or rejected?"
- What we have in the proposal so far looks great. Tiffany has two other sections we could consider adding: (1) Usage and (2) Dependencies. [See her repo for an example](https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1)

**Comment by aakanksha023** [comment]
EDA: 
- Issue regarding overplotting for `Ethnicity` and `Education level` resolved by removing size=40 argument [link_to_commit](https://github.com/UBC-MDS/DSCI_522_Group_412/pull/9/commits/10961f2962cc17998522f9e345a1947e132df215)
- `BankCustomer` histogram: Unable to debug why function make_plot() is not reading the the two categories properly. 
       - Debugging attempt no. 1: Verified that the data type(s) is the same as other categorical column. make_plot() reads the variables as the correct type ie. nominal
