### ISSUE TITLE
Feedback from Jarvis and Ryan

### ISSUE THREAD

**Issue by alistair-clark** [UBC-MDS/DSCI_522_Group_412#29]
- Add comments about precision vs. recall. Talk about why precision is an important measure because of the False Positive
- Consider whether or not PCA was done on the dataset, because that would limit our ability to do feature engineering. Maybe clustering or other unsupervised learning?
- To improve errors it might be good to pull in information from other sources to add additional features (or data). 
- Do hyperparameter search or ensemble model to correctly classify a few more datapoints.
- Question about the approach = do we really want to try and match performance? Or do we want to try and predict whether or not the human made the correct decision.

**Comment by aakanksha023** [comment]
- Thanks! 
              - Suggestions addressed in the report.
