### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by rita-ni** [UBC-MDS/DSCI_522_Group_412#30]
- the EDA is great,  especially for the numerical variables. The EDA for some categorical variables is a little confusing since we don't know what does the label means.  The ROC report and the confusion matrix is very easy to understand the performance of the model.
- Since some of the features are not very helpful for prediction, it would be better to see some work in feature selection.

**Comment by aakanksha023** [comment]
Thank you!
Merged in tasks for milestone 3.
